
resolver: lts-13.3

packages:
- '.'

- location:
    git: https://github.com/Haskell-mouse/accelerate-fft.git
    commit: 5c19c3865a7cc6adc23cdc33b6c3e93e2667129a
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate.git
    commit: cfa1f48bef0e8d5bf2bec60a11ade2cac2153a9d
  extra-dep: true

- location:
    git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: e0f1a7676d160168440ed8338f2054014976646b
  extra-dep: true
  subdirs:
    - accelerate-llvm
    - accelerate-llvm-native
    - accelerate-llvm-ptx  

- location: 
    git: https://github.com/tmcdonell/lens-accelerate
    commit: b74eb8098735b1ad6cff3c5655af03d3f29b9f8e
  extra-dep: true

extra-deps: 
  - continued-fractions-0.10.0.2
  - converge-0.1.0.1
  - llvm-hs-8.0.0
  - gamma-0.10.0.0
  - llvm-hs-pure-8.0.0



# Override default flag values for local packages and extra-deps
flags:
      accelerate:
                       unsafe-checks: false
                       bounds-checks: false
                       debug: false
                       internal-checks: false


# Extra package databases containing global packages
extra-package-dbs: []

extra-lib-dirs: 
  - /usr/local/cuda-10.0/lib64

